"""initial domain tables

Revision ID: ec24a3719c3b
Revises:
Create Date: 2026-07-19 08:03:21.692089
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ec24a3719c3b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("current_stage", sa.String(length=100), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'needs_review', 'done', 'error')",
            name="ck_pipeline_runs_state",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_runs_state_created", "pipeline_runs", ["state", "created_at"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_ref", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_ref"),
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teacher_ref", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("teacher_ref"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_ref", sa.String(length=255), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("subject_type", sa.String(length=100), nullable=False),
        sa.Column("subject_ref", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_role IN ('case_manager', 'teacher', 'provider', 'system')",
            name="ck_audit_events_actor_role",
        ),
        sa.ForeignKeyConstraint(["pipeline_run_id"], ["pipeline_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"], unique=False)
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False)
    op.create_index(
        "ix_audit_events_pipeline_run_id", "audit_events", ["pipeline_run_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_subject", "audit_events", ["subject_type", "subject_ref"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION prevent_audit_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only; % is forbidden', TG_OP;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_audit_event_mutation()
        """
    )
    op.create_table(
        "classes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("class_ref", sa.String(length=255), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("school_year", sa.String(length=9), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "school_year ~ '^[0-9]{4}-[0-9]{4}$'", name="ck_classes_school_year_format"
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_ref"),
    )
    op.create_index("ix_classes_teacher_id", "classes", ["teacher_id"], unique=False)
    op.create_table(
        "iep_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("iep_record_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_run_id", sa.Uuid(), nullable=False),
        sa.Column("approval_state", sa.String(length=16), nullable=False),
        sa.Column("is_current_approved", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("disability_category", sa.String(length=255), nullable=False),
        sa.Column("school_year", sa.String(length=9), nullable=False),
        sa.Column("annual_review", sa.Date(), nullable=True),
        sa.Column("triennial_reeval", sa.Date(), nullable=True),
        sa.Column("last_progress_report", sa.Date(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(approval_state = 'draft' AND approved_at IS NULL "
            "AND is_current_approved = false AND superseded_at IS NULL) OR "
            "(approval_state = 'approved' AND approved_at IS NOT NULL "
            "AND ((is_current_approved = true AND superseded_at IS NULL) OR "
            "(is_current_approved = false AND superseded_at IS NOT NULL)))",
            name="ck_iep_records_approval_lifecycle",
        ),
        sa.CheckConstraint(
            "approval_state IN ('draft', 'approved')", name="ck_iep_records_approval_state"
        ),
        sa.CheckConstraint(
            "school_year ~ '^[0-9]{4}-[0-9]{4}$'", name="ck_iep_records_school_year_format"
        ),
        sa.CheckConstraint("version >= 1", name="ck_iep_records_positive_version"),
        sa.ForeignKeyConstraint(["pipeline_run_id"], ["pipeline_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extraction_run_id"),
        sa.UniqueConstraint("iep_record_id", "version", name="uq_iep_records_lineage_version"),
        sa.UniqueConstraint("pipeline_run_id"),
    )
    op.create_index("ix_iep_records_annual_review", "iep_records", ["annual_review"], unique=False)
    op.create_index(
        "ix_iep_records_lineage_version", "iep_records", ["iep_record_id", "version"], unique=False
    )
    op.create_index("ix_iep_records_student_id", "iep_records", ["student_id"], unique=False)
    op.create_index(
        "ix_iep_records_triennial_reeval", "iep_records", ["triennial_reeval"], unique=False
    )
    op.create_index(
        "uq_iep_records_current_approved",
        "iep_records",
        ["iep_record_id"],
        unique=True,
        postgresql_where=sa.text("is_current_approved = true"),
    )
    op.create_table(
        "briefs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("iep_record_version_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("rules_version", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'released', 'confirmed', 'flagged')", name="ck_briefs_status"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["iep_record_version_id"], ["iep_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "iep_record_version_id",
            "teacher_id",
            "class_id",
            name="uq_briefs_version_teacher_class",
        ),
    )
    op.create_index("ix_briefs_teacher_status", "briefs", ["teacher_id", "status"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("school_year", sa.String(length=9), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "school_year ~ '^[0-9]{4}-[0-9]{4}$'", name="ck_enrollments_school_year_format"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "class_id", "school_year", name="uq_enrollments_student_class_year"
        ),
    )
    op.create_index("ix_enrollments_class_id", "enrollments", ["class_id"], unique=False)
    op.create_index("ix_enrollments_student_id", "enrollments", ["student_id"], unique=False)
    op.create_table(
        "obligations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("iep_record_version_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("accommodation_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=255), nullable=False),
        sa.Column("citation", sa.Text(), nullable=False),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column("practice_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'confirmed' AND confirmed_at IS NOT NULL "
            "AND flag_reason IS NULL) OR "
            "(status = 'flagged' AND confirmed_at IS NULL "
            "AND flag_reason IS NOT NULL) OR "
            "(status = 'pending' AND confirmed_at IS NULL AND flag_reason IS NULL)",
            name="ck_obligations_status_details",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'flagged')", name="ck_obligations_status"
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["iep_record_version_id"], ["iep_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "iep_record_version_id",
            "teacher_id",
            "class_id",
            "accommodation_id",
            "rule_id",
            name="uq_obligations_derivation",
        ),
    )
    op.create_index(
        "ix_obligations_accommodation_id", "obligations", ["accommodation_id"], unique=False
    )
    op.create_index("ix_obligations_class_id", "obligations", ["class_id"], unique=False)
    op.create_index(
        "ix_obligations_teacher_status", "obligations", ["teacher_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_obligations_teacher_status", table_name="obligations")
    op.drop_index("ix_obligations_class_id", table_name="obligations")
    op.drop_index("ix_obligations_accommodation_id", table_name="obligations")
    op.drop_table("obligations")
    op.drop_index("ix_enrollments_student_id", table_name="enrollments")
    op.drop_index("ix_enrollments_class_id", table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index("ix_briefs_teacher_status", table_name="briefs")
    op.drop_table("briefs")
    op.drop_index(
        "uq_iep_records_current_approved",
        table_name="iep_records",
        postgresql_where=sa.text("is_current_approved = true"),
    )
    op.drop_index("ix_iep_records_triennial_reeval", table_name="iep_records")
    op.drop_index("ix_iep_records_student_id", table_name="iep_records")
    op.drop_index("ix_iep_records_lineage_version", table_name="iep_records")
    op.drop_index("ix_iep_records_annual_review", table_name="iep_records")
    op.drop_table("iep_records")
    op.drop_index("ix_classes_teacher_id", table_name="classes")
    op.drop_table("classes")
    op.execute("DROP TRIGGER audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION prevent_audit_event_mutation()")
    op.drop_index("ix_audit_events_subject", table_name="audit_events")
    op.drop_index("ix_audit_events_pipeline_run_id", table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_event_type", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("teachers")
    op.drop_table("students")
    op.drop_index("ix_pipeline_runs_state_created", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
